[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "overpass"
dynamic = ["version"]
description = "Python wrapper for the OpenStreetMap Overpass API"
readme = "README.md"
license.file = "LICENSE.txt"
authors = [
    { name = "Martijn van Exel", email = "m@rtijn.org" },
]
keywords = [
    "openstreetmap",
    "overpass",
    "wrapper",
]
classifiers = [
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Scientific/Engineering :: GIS",
    "Topic :: Utilities",
]
dependencies = [
    "geojson>=1.0.9",
    "requests>=2.3.0",
    "shapely>=1.6.4",
]

[project.optional-dependencies]
test = [
    "pytest"
]

[project.urls]
Homepage = "https://github.com/mvexel/overpass-api-python-wrapper"

[tool.hatch.version]
path = "overpass/__init__.py"

[tool.hatch.build.targets.sdist]
include = [
    "/overpass",
]

